apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contentful.net 
  description: .NET library for the Contentful Content Delivery API, Content Preview API, and the Contentful Management API.
  annotations:
    github.com/project-slug: contentful/contentful.net 
    contentful.com/service-tier: "4"
  tags:
    - tier-4
spec:
  type: library 
  lifecycle: production
  owner: group:team-developer-experience
